BEGIN;
CREATE TABLE expense_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES businesses(id), name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 160), is_active boolean NOT NULL DEFAULT true, is_system boolean NOT NULL DEFAULT false, UNIQUE(business_id,name));
CREATE TABLE expenses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES businesses(id), branch_id uuid NOT NULL REFERENCES branches(id), category_id uuid NOT NULL REFERENCES expense_categories(id), description text, payee text, provider text, provider_reference text, status text NOT NULL DEFAULT 'POSTED' CHECK(status='POSTED'), amount_minor bigint NOT NULL CHECK(amount_minor > 0), currency_code char(3) NOT NULL, method text NOT NULL CHECK(method IN ('CASH','MOMO','CARD','BANK','OTHER')), actor_staff_id uuid NOT NULL REFERENCES staff(id), client_mutation_id text NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(business_id,client_mutation_id));
CREATE TABLE cashbook_adjustments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES businesses(id), branch_id uuid NOT NULL REFERENCES branches(id), reason text NOT NULL CHECK(reason IN ('OPENING_BALANCE','CORRECTION','OWNER_INJECTION','OWNER_WITHDRAWAL')), note text NOT NULL, amount_delta_minor bigint NOT NULL CHECK(amount_delta_minor <> 0), currency_code char(3) NOT NULL, method text NOT NULL CHECK(method IN ('CASH','MOMO','CARD','BANK','OTHER')), actor_staff_id uuid NOT NULL REFERENCES staff(id), client_mutation_id text NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(business_id,client_mutation_id));
ALTER TABLE cashbook_adjustments ADD CHECK ((reason IN ('OPENING_BALANCE','OWNER_INJECTION') AND amount_delta_minor > 0) OR (reason='OWNER_WITHDRAWAL' AND amount_delta_minor < 0) OR reason='CORRECTION');
CREATE TABLE cashbook_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES businesses(id), branch_id uuid NOT NULL REFERENCES branches(id), amount_delta_minor bigint NOT NULL CHECK(amount_delta_minor <> 0), currency_code char(3) NOT NULL, method text NOT NULL CHECK(method IN ('CASH','MOMO','CARD','BANK','OTHER')), entry_type text NOT NULL CHECK(entry_type IN ('SALE_RECEIPT','CUSTOMER_PAYMENT','PURCHASE_PAYMENT','SUPPLIER_PAYMENT','SALE_REFUND','PURCHASE_RETURN_RECOVERY','EXPENSE','OPENING_BALANCE','ADJUSTMENT','OWNER_INJECTION','OWNER_WITHDRAWAL')), source_type text NOT NULL, source_id uuid NOT NULL, actor_staff_id uuid REFERENCES staff(id), idempotency_key text NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(business_id,idempotency_key));
CREATE INDEX idx_expenses_branch_time ON expenses(business_id,branch_id,occurred_at DESC,id DESC);
CREATE INDEX idx_expenses_method_time ON expenses(business_id,method,occurred_at DESC);
CREATE INDEX idx_cashbook_adjustments_branch_time ON cashbook_adjustments(business_id,branch_id,occurred_at DESC,id DESC);
CREATE INDEX idx_cashbook_adjustments_method_time ON cashbook_adjustments(business_id,method,occurred_at DESC);
CREATE INDEX idx_cashbook_entries_branch_time ON cashbook_entries(business_id,branch_id,occurred_at DESC,id DESC);
CREATE INDEX idx_cashbook_entries_method_time ON cashbook_entries(business_id,method,occurred_at DESC);
CREATE FUNCTION ensure_expense_categories(target_business uuid) RETURNS void LANGUAGE sql AS $$ INSERT INTO expense_categories(business_id,name,is_system) SELECT target_business,name,true FROM (VALUES ('Rent'),('Utilities'),('Transport & Fuel'),('Wages & Staff'),('Repairs & Maintenance'),('Marketing'),('Fees & Charges'),('Cleaning & Sanitation'),('Permits & Taxes'),('Food & Refreshments'),('Miscellaneous')) defaults(name) ON CONFLICT(business_id,name) DO NOTHING; $$;
SELECT ensure_expense_categories(id) FROM businesses;
CREATE FUNCTION seed_business_expense_categories() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN PERFORM ensure_expense_categories(NEW.id); RETURN NEW; END; $$;
CREATE TRIGGER business_expense_defaults AFTER INSERT ON businesses FOR EACH ROW EXECUTE FUNCTION seed_business_expense_categories();
-- Original receipts remain gross for REVERSED/PARTIALLY_REVERSED payments.
-- Only SUCCEEDED concrete refund transactions subtract money (ORIGINAL_METHOD
-- is expanded before persistence). Credit and pending movements are excluded.
INSERT INTO cashbook_entries(business_id,branch_id,amount_delta_minor,currency_code,method,entry_type,source_type,source_id,actor_staff_id,idempotency_key,occurred_at) SELECT * FROM (SELECT p.business_id,p.branch_id,p.amount_minor,p.currency_code,p.method,'SALE_RECEIPT','PAYMENT',p.id,s.cashier_staff_id,'sale-payment:'||p.id,p.received_at FROM payments p JOIN sales s ON s.id=p.sale_id WHERE p.amount_minor>0 AND p.status IN ('SUCCEEDED','REVERSED','PARTIALLY_REVERSED')) movement WHERE method IN ('CASH','MOMO','CARD','BANK','OTHER') ON CONFLICT(business_id,idempotency_key) DO NOTHING;
INSERT INTO cashbook_entries(business_id,branch_id,amount_delta_minor,currency_code,method,entry_type,source_type,source_id,actor_staff_id,idempotency_key,occurred_at) SELECT * FROM (SELECT business_id,branch_id,amount_minor,currency_code,method,'CUSTOMER_PAYMENT','CUSTOMER_PAYMENT',id,actor_staff_id,'customer-payment:'||id,received_at FROM customer_payments WHERE amount_minor>0 AND status='SUCCEEDED') movement WHERE method IN ('CASH','MOMO','CARD','BANK','OTHER') ON CONFLICT(business_id,idempotency_key) DO NOTHING;
INSERT INTO cashbook_entries(business_id,branch_id,amount_delta_minor,currency_code,method,entry_type,source_type,source_id,actor_staff_id,idempotency_key,occurred_at) SELECT * FROM (SELECT business_id,branch_id,-total_minor,currency_code,settlement_method AS method,'PURCHASE_PAYMENT','PURCHASE',id,received_by_staff_id,'purchase:'||id,received_at FROM purchases WHERE status='RECEIVED' AND total_minor>0) movement WHERE method IN ('CASH','MOMO','CARD','BANK','OTHER') ON CONFLICT(business_id,idempotency_key) DO NOTHING;
INSERT INTO cashbook_entries(business_id,branch_id,amount_delta_minor,currency_code,method,entry_type,source_type,source_id,actor_staff_id,idempotency_key,occurred_at) SELECT * FROM (SELECT business_id,branch_id,balance_delta_minor,currency_code,method,'SUPPLIER_PAYMENT','SUPPLIER_PAYMENT',id,actor_staff_id,'supplier-payment:'||id,occurred_at FROM supplier_payable_ledger WHERE balance_delta_minor<0 AND source_type='PAYMENT') movement WHERE method IN ('CASH','MOMO','CARD','BANK','OTHER') ON CONFLICT(business_id,idempotency_key) DO NOTHING;
INSERT INTO cashbook_entries(business_id,branch_id,amount_delta_minor,currency_code,method,entry_type,source_type,source_id,actor_staff_id,idempotency_key,occurred_at) SELECT * FROM (SELECT r.business_id,c.branch_id,-r.amount_minor,r.currency_code,r.method,'SALE_REFUND','REFUND_TRANSACTION',r.id,c.initiated_by_staff_id,'refund:'||r.id,COALESCE(r.completed_at,r.created_at) FROM refund_transactions r JOIN return_cases c ON c.id=r.return_case_id WHERE r.amount_minor>0 AND r.status='SUCCEEDED') movement WHERE method IN ('CASH','MOMO','CARD','BANK','OTHER') ON CONFLICT(business_id,idempotency_key) DO NOTHING;
INSERT INTO cashbook_entries(business_id,branch_id,amount_delta_minor,currency_code,method,entry_type,source_type,source_id,actor_staff_id,idempotency_key,occurred_at) SELECT * FROM (SELECT business_id,branch_id,supplier_recovery_minor,currency_code,recovery_method AS method,'PURCHASE_RETURN_RECOVERY','PURCHASE_RETURN',id,returned_by_staff_id,'purchase-return:'||id,occurred_at FROM purchase_return_cases WHERE supplier_recovery_minor>0) movement WHERE method IN ('CASH','MOMO','CARD','BANK','OTHER') ON CONFLICT(business_id,idempotency_key) DO NOTHING;
COMMIT;
