"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { clientApi, messageFrom } from '../lib/client-api';
import { enqueueMutation, flushPendingMutations, getOrCreateClientId, mutationAppliedEvent } from '../lib/offline-sync';
export type MoneyAccount={id:string;branchId:string|null;name:string;method:string;kind:string;currencyCode:string;active:boolean;allowNegative:boolean;balanceMinor:number};
type Default={branchId:string;method:string;moneyAccountId:string};
type Reconciliation={id:string;status:string;differenceMinor:number;moneyAccountId:string;periodEnd:string};
const methods=['CASH','MOMO','CARD','BANK','OTHER'];
export function Treasury({businessId,branchId,currencyCode,role,onAccounts}:{businessId:string;branchId:string;currencyCode:string;role:string;onAccounts:(a:MoneyAccount[])=>void}) {
 const elevated=['OWNER','ADMIN','MANAGER','ACCOUNTANT'].includes(role);
 const [accounts,setAccounts]=useState<MoneyAccount[]>([]),[defaults,setDefaults]=useState<Default[]>([]),[reconciliations,setReconciliations]=useState<Reconciliation[]>([]);
 const [message,setMessage]=useState(''),[version,setVersion]=useState(0),[name,setName]=useState(''),[method,setMethod]=useState('CASH'),[wide,setWide]=useState(false),[negative,setNegative]=useState(false);
 const [source,setSource]=useState(''),[destination,setDestination]=useState(''),[amount,setAmount]=useState(''),[account,setAccount]=useState(''),[observed,setObserved]=useState(''),[type,setType]=useState('CASH_COUNT'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[note,setNote]=useState('');
 const cacheKey=`tradeos.treasury.v1:${businessId}:${branchId}:${role}`;
 useEffect(()=>{
  setAccounts([]);setDefaults([]);setReconciliations([]);onAccounts([]);
  let alive=true;const update=(data:{accounts:MoneyAccount[];defaults:Default[];reconciliations:Reconciliation[]})=>{if(alive){setAccounts(data.accounts);setDefaults(data.defaults);setReconciliations(data.reconciliations);onAccounts(data.accounts);}};
  try{const cached=localStorage.getItem(cacheKey);if(cached)update(JSON.parse(cached));}catch{}
  const load=async()=>{try{const query=`businessId=${businessId}${role==='CASHIER'?`&branchId=${branchId}`:''}`;const [a,d,r]=await Promise.all([clientApi<{accounts:MoneyAccount[]}>(`/api/tradeos/v1/money-accounts?${query}`),clientApi<{defaults:Default[]}>(`/api/tradeos/v1/money-account-defaults?businessId=${businessId}&branchId=${branchId}`),clientApi<{reconciliations:Reconciliation[]}>(`/api/tradeos/v1/money-reconciliations?${query}`)]);const data={...a,...d,...r};update(data);if(alive)localStorage.setItem(cacheKey,JSON.stringify(data));}catch(e){if(alive)setMessage(messageFrom(e));}};
  if(navigator.onLine)void load();const refresh=()=>void load();window.addEventListener(mutationAppliedEvent,refresh);window.addEventListener('online',refresh);return()=>{alive=false;window.removeEventListener(mutationAppliedEvent,refresh);window.removeEventListener('online',refresh);};
 },[businessId,branchId,role,cacheKey,version,onAccounts]);
 const money=(n:number)=>`${currencyCode} ${(n/100).toFixed(2)}`;
 const minor=(s:string)=>{if(!/^-?\d+(\.\d{1,2})?$/.test(s))throw new Error('Enter an amount with at most two decimal places');const negative=s.startsWith('-');const [whole,fraction='']=s.replace(/^-/,'').split('.');const n=Number((BigInt(whole!)*100n+BigInt(fraction.padEnd(2,'0')))*(negative?-1n:1n));if(!Number.isSafeInteger(n))throw new Error('Amount is too large');return n;};
 const queue=(mutationType:string,payload:unknown)=>{try{enqueueMutation({businessId,branchId,clientId:getOrCreateClientId(),clientMutationId:crypto.randomUUID(),mutationType,occurredAt:new Date().toISOString(),payload});setMessage('Saved on this device. Treasury updates after sync.');void flushPendingMutations().catch(e=>setMessage(messageFrom(e)));}catch(e){setMessage(messageFrom(e));}};
 const write=async(path:string,httpMethod:string,payload:unknown)=>{try{await clientApi(`/api/tradeos/v1/${path}`,{method:httpMethod,body:JSON.stringify(payload)});setVersion(v=>v+1);setMessage('Saved');}catch(e){setMessage(messageFrom(e));}};
 const create=(e:FormEvent)=>{e.preventDefault();void write('money-accounts','POST',{businessId,branchId:wide?null:branchId,name,method,kind:({CASH:'CASH_DRAWER',MOMO:'MOMO_WALLET',CARD:'CARD_CLEARING',BANK:'BANK_ACCOUNT',OTHER:'OTHER'} as Record<string,string>)[method],currencyCode,allowNegative:negative});};
 const eligible=accounts.filter(a=>a.active&&(role!=='CASHIER'||(a.branchId===branchId&&a.method==='CASH'&&a.kind==='CASH_DRAWER')));
 return <div className="treasury-section"><h3>Treasury</h3><p>Current account balances cover all posted history. Period cashbook net movement is shown separately above.</p><p>{role==='CASHIER'?'Current branch account total':'Total business net movement across all history'}: <strong>{money(accounts.reduce((s,a)=>s+a.balanceMinor,0))}</strong></p>
 <div className="form-row">{methods.map(m=><p key={m}>{m}: {money(accounts.filter(a=>a.method===m).reduce((s,a)=>s+a.balanceMinor,0))}</p>)}</div>
 <div className="treasury-table-scroll"><table><thead><tr><th>Account</th><th>Scope</th><th>Method</th><th>Balance</th><th>Status</th>{elevated&&<th>Manage</th>}</tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.name}</td><td>{a.branchId? a.branchId===branchId?'Current branch':'Other branch':'Business'}</td><td>{a.method}</td><td>{money(a.balanceMinor)}</td><td>{a.active?'Active':'Inactive'}</td>{elevated&&<td><button onClick={()=>{const renamed=window.prompt('Account name',a.name);if(renamed)void write(`money-accounts/${a.id}`,'PATCH',{businessId,name:renamed});}}>Rename</button><button onClick={()=>void write(`money-accounts/${a.id}`,'PATCH',{businessId,active:!a.active})}>{a.active?'Deactivate':'Activate'}</button></td>}</tr>)}</tbody></table></div>
 {elevated&&<><form onSubmit={create}><h4>Create account (online)</h4><label>Name<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option key={m}>{m}</option>)}</select></label><label><input type="checkbox" checked={wide} onChange={e=>setWide(e.target.checked)}/>Business-wide</label><label><input type="checkbox" checked={negative} onChange={e=>setNegative(e.target.checked)}/>Allow negative transfer source balance</label><button>Create account</button></form>
 <h4>Current branch defaults (online)</h4>{methods.map(m=><label key={m}>{m}<select value={defaults.find(d=>d.method===m)?.moneyAccountId??''} onChange={e=>void write('money-account-defaults','PUT',{businessId,branchId,method:m,moneyAccountId:e.target.value})}><option value="">Choose account</option>{accounts.filter(a=>a.active&&a.method===m&&(a.branchId===null||a.branchId===branchId)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}
 <form onSubmit={e=>{e.preventDefault();try{queue('MONEY_TRANSFER_CREATE',{sourceAccountId:source,destinationAccountId:destination,amountMinor:minor(amount),note});}catch(error){setMessage(messageFrom(error));}}}><h4>Transfer funds</h4><label>From<select required value={source} onChange={e=>setSource(e.target.value)}><option value="">Choose source</option>{eligible.map(a=><option key={a.id} value={a.id}>{a.name} · {a.method} · {money(a.balanceMinor)}</option>)}</select></label><label>To<select required value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose destination</option>{eligible.filter(a=>a.id!==source).map(a=><option key={a.id} value={a.id}>{a.name} · {a.method}</option>)}</select></label><label>Amount<input required value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/></label><button>Save transfer</button></form></>}
 {(elevated||role==='CASHIER')&&<form onSubmit={e=>{e.preventDefault();try{queue('MONEY_RECONCILIATION_CREATE',{moneyAccountId:account,type:role==='CASHIER'?'CASH_COUNT':type,periodStart:new Date(start).toISOString(),periodEnd:new Date(end).toISOString(),observedBalanceMinor:minor(observed),note});}catch(error){setMessage(messageFrom(error));}}}><h4>{role==='CASHIER'?'Cash drawer count':'Start reconciliation'}</h4><label>Account<select required value={account} onChange={e=>setAccount(e.target.value)}><option value="">Choose account</option>{eligible.filter(a=>type!=='CASH_COUNT'||(a.method==='CASH'&&a.kind==='CASH_DRAWER')).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{elevated&&<label>Type<select value={type} onChange={e=>{setType(e.target.value);setAccount('');}}><option>CASH_COUNT</option><option>STATEMENT</option></select></label>}<label>Period start<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Period end<input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Observed balance<input required value={observed} onChange={e=>setObserved(e.target.value)} inputMode="decimal"/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></label><p>Variances stay open until explicitly resolved. Resolution posts a correction for the exact difference.</p><button>Save reconciliation</button></form>}
 <h4>Reconciliations</h4>{reconciliations.map(r=><p key={r.id}>{accounts.find(a=>a.id===r.moneyAccountId)?.name} · {r.status} · Difference {money(r.differenceMinor)} {elevated&&r.status==='VARIANCE'&&<button onClick={()=>{const resolutionNote=window.prompt('Required explanation for the correction');if(resolutionNote?.trim())queue('MONEY_RECONCILIATION_RESOLVE',{reconciliationId:r.id,note:resolutionNote});}}>Resolve with correction</button>}</p>)}{message&&<p role="status">{message}</p>}
 </div>;
}
