import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { buildApp } from "../src/app.js";
import { createPool, withTransaction } from "../src/db.js";
import { recordCashbookEntry, cashMethods } from "../src/commerce/cashbook.js";
import { applyReconciliationMutation } from "../src/commerce/reconciliation.js";
// Truncating suite: use only a disposable PostgreSQL database with migrations 0001–0009.
process.env.DATABASE_URL ??= "postgresql://tradeos:tradeos@127.0.0.1:5432/tradeos_ci";
const pool=createPool(),app=buildApp(pool);
beforeAll(async()=>{await app.ready();});
beforeEach(async()=>{await pool.query("TRUNCATE app_users,businesses CASCADE");});
afterAll(async()=>{await app.close();await pool.end();});
const counts=(cash=0,momo=0)=>cashMethods.map(method=>({method,countedMinor:method==="CASH" ? cash : method==="MOMO" ? momo : 0}));
async function fixture() {
  const registered=await app.inject({method:"POST",url:"/v1/auth/register",payload:{displayName:"Owner",email:"operations@tradeos.test",password:"TradeOS-Test-1234",platform:"WEB",deviceKey:"operations-device",appVersion:"test"}});
  expect(registered.statusCode).toBe(201);
  const headers={authorization:`Bearer ${registered.json().session.accessToken}`};
  const onboard=await app.inject({method:"POST",url:"/v1/onboarding/business",headers,payload:{name:"Operations Shop",businessType:"RETAIL_HARDWARE",branchName:"Main"}});
  expect(onboard.statusCode).toBe(201);
  const businessId=onboard.json().business.id,branchId=onboard.json().branch.id;
  const actor=(await pool.query(`SELECT staff_id FROM business_memberships WHERE business_id=$1`,[businessId])).rows[0].staff_id;
  const request=(key:string,type:string,payload:unknown,time="2026-10-06T09:00:00Z",branch=branchId)=>app.inject({method:"POST",url:"/v1/sync",headers,payload:{mutations:[{businessId,branchId:branch,clientId:"operations-device",clientMutationId:key,mutationType:type,occurredAt:time,payload}]}});
  const sync=async(key:string,type:string,payload:unknown,time?:string,branch?:string)=>{const r=await request(key,type,payload,time,branch);expect(r.statusCode).toBe(200);return r.json().mutationResults[0];};
  const get=(resource:string,suffix="")=>app.inject({method:"GET",url:`/v1/operations/${resource}?businessId=${businessId}&branchId=${branchId}${suffix}`,headers});
  const applied=async(key:string,type:string,payload:unknown,time?:string)=>{const r=await sync(key,type,payload,time);expect(r.status,r.errorMessage).toBe("APPLIED");return r.result;};
  const post=async(url:string,payload:unknown)=>{const r=await app.inject({method:"POST",url,headers,payload});expect(r.statusCode).toBe(201);return r.json();};
  return {businessId,branchId,actor,headers,request,sync,get,applied,post};
}
describe("operating days and staff shifts",()=>{
  it("reconciles custody snapshots, real movements and late offline entries on closed intervals",async()=>{
    const f=await fixture();
    const opening={businessDate:"2026-10-06",openingBalances:[{method:"CASH",countedMinor:10000},{method:"MOMO",countedMinor:5000}],actorStaffId:randomUUID(),note:"Opening custody"};
    const day=await f.applied("day-open","OPERATING_DAY_OPEN_CREATE",opening);
    const shift=await f.applied("shift-open","SHIFT_OPEN_CREATE",{openingBalances:[{method:"CASH",countedMinor:2000}],actorStaffId:randomUUID(),staffId:randomUUID()},"2026-10-06T09:01:00Z");
    expect((await pool.query(`SELECT COUNT(*) FROM cashbook_entries`)).rows[0].count).toBe("0");
    const initial=(await f.get("current")).json();expect(initial.openShiftCount).toBe(1);expect(initial.operatingDay.balances).toHaveLength(5);
    expect(initial.operatingDay.balances.find((b:any)=>b.method==="CASH").expectedClosingMinor).toBe(10000);
    expect(initial.operatingDay.balances.find((b:any)=>b.method==="MOMO").expectedClosingMinor).toBe(5000);
    expect(initial.shift.staffId).toBe(f.actor);
    expect(initial.operatingDay.openedByStaffId).toBe(f.actor);
    expect(initial.shift.balances.find((b:any)=>b.method==="CASH").expectedClosingMinor).toBe(2000);
    expect((await f.applied("day-open","OPERATING_DAY_OPEN_CREATE",opening)).id).toBe(day.id);
    expect((await f.applied("shift-open","SHIFT_OPEN_CREATE",{})).id).toBe(shift.id);
    expect((await applyReconciliationMutation(pool,{businessId:f.businessId,branchId:f.branchId,clientMutationId:"day-open",occurredAt:"2026-10-06T09:00:00Z"},{...opening,actorStaffId:f.actor},"OPERATING_DAY_OPEN_CREATE")).idempotentReplay).toBe(true);
    const customerId=(await f.post("/v1/customers",{businessId:f.businessId,name:"Customer",creditLimitMinor:10000})).customer.id;
    const supplierId=(await f.post("/v1/suppliers",{businessId:f.businessId,name:"Supplier"})).supplier.id;
    const itemId=(await f.post("/v1/catalog/items",{businessId:f.businessId,name:"Item",kind:"PRODUCT",trackStock:true,stockUnitCode:"each",units:[{code:"each",label:"Each",canStock:true,canPurchase:true,canSell:true,defaultSalePriceMinor:1000}]})).item.id;
    await f.applied("supplier-credit","PURCHASE_RECEIVE_CREATE",{supplierId,settlementMethod:"SUPPLIER_CREDIT",lines:[{itemId,purchaseUnitCode:"each",quantity:4,unitCostMinor:300}]},"2026-10-06T10:00:00Z");
    await f.applied("credit-sale","SALE_CREATE",{customerId,paymentMethod:"CUSTOMER_CREDIT",lines:[{itemId,saleUnitCode:"each",quantity:1}]},"2026-10-06T10:01:00Z");
    expect((await pool.query(`SELECT COUNT(*) FROM cashbook_entries`)).rows[0].count).toBe("0");
    await f.applied("cash-sale","SALE_CREATE",{paymentMethod:"CASH",lines:[{itemId,saleUnitCode:"each",quantity:1}]},"2026-10-06T10:02:00Z");
    const categoryId=(await pool.query(`SELECT id FROM expense_categories WHERE business_id=$1 LIMIT 1`,[f.businessId])).rows[0].id;
    await f.applied("expense","EXPENSE_CREATE",{categoryId,amountMinor:300,method:"CASH",description:"Transport"},"2026-10-06T10:03:00Z");
    await f.applied("momo","CUSTOMER_PAYMENT_CREATE",{customerId,amountMinor:400,method:"MOMO"},"2026-10-06T10:04:00Z");
    const live=(await f.get("current")).json();
    expect(live.operatingDay.balances.find((b:any)=>b.method==="CASH")).toMatchObject({movementMinor:700,expectedClosingMinor:10700});
    expect(live.shift.balances.find((b:any)=>b.method==="CASH").expectedClosingMinor).toBe(2700);
    expect(live.operatingDay.balances.find((b:any)=>b.method==="MOMO").expectedClosingMinor).toBe(5400);
    expect(live.shift.balances.find((b:any)=>b.method==="MOMO").expectedClosingMinor).toBe(400);
    expect((await f.sync("day-blocked","OPERATING_DAY_CLOSE_CREATE",{dayId:day.id,closingBalances:counts(10650,5400)},"2026-10-06T18:00:00Z")).status).toBe("REJECTED");
    expect((await f.sync("missing","SHIFT_CLOSE_CREATE",{shiftId:shift.id,closingBalances:[{method:"CASH",countedMinor:2600}]},"2026-10-06T17:00:00Z")).status).toBe("REJECTED");
    expect((await f.sync("early","SHIFT_CLOSE_CREATE",{shiftId:shift.id,closingBalances:counts()},"2026-10-06T08:00:00Z")).status).toBe("REJECTED");
    const close={shiftId:shift.id,closingBalances:counts(2600,400),actorStaffId:randomUUID()};
    await f.applied("shift-close","SHIFT_CLOSE_CREATE",close,"2026-10-06T17:00:00Z");
    await f.applied("shift-close","SHIFT_CLOSE_CREATE",close,"2026-10-06T17:00:00Z");
    const context={businessId:f.businessId,branchId:f.branchId,clientMutationId:"shift-close",occurredAt:"2026-10-06T17:00:00Z"};
    expect((await applyReconciliationMutation(pool,context,{...close,actorStaffId:f.actor},"SHIFT_CLOSE_CREATE")).idempotentReplay).toBe(true);
    await f.applied("day-close","OPERATING_DAY_CLOSE_CREATE",{dayId:day.id,closingBalances:counts(10650,5400)},"2026-10-06T18:00:00Z");
    await f.applied("day-close","OPERATING_DAY_CLOSE_CREATE",{dayId:day.id,closingBalances:counts(10650,5400)},"2026-10-06T18:00:00Z");
    let days=(await f.get("days")).json().days,shifts=(await f.get("shifts",`&dayId=${day.id}`)).json().shifts;
    expect(days[0].balances.find((b:any)=>b.method==="CASH").varianceMinor).toBe(-50);
    expect(shifts[0].balances.find((b:any)=>b.method==="CASH").varianceMinor).toBe(-100);
    expect(shifts[0].closedByStaffId).toBe(f.actor);
    expect(shifts[0].balances).toHaveLength(5);
    expect(shifts[0].closedAt).toBe("2026-10-06T17:00:00.000Z");
    expect(days[0].closedAt).toBe("2026-10-06T18:00:00.000Z");
    for(const b of shifts[0].balances) if(b.method!=="CASH")expect(b.varianceMinor).toBe(0);
    await f.applied("late","EXPENSE_CREATE",{categoryId,amountMinor:100,method:"CASH",description:"Offline transport"},"2026-10-06T16:00:00Z");
    await f.applied("late","EXPENSE_CREATE",{categoryId,amountMinor:100,method:"CASH",description:"Offline transport"},"2026-10-06T16:00:00Z");
    days=(await f.get("days")).json().days;shifts=(await f.get("shifts")).json().shifts;
    expect(days[0].balances.find((b:any)=>b.method==="CASH")).toMatchObject({movementMinor:600,expectedClosingMinor:10600,varianceMinor:50});
    expect(shifts[0].balances.find((b:any)=>b.method==="CASH")).toMatchObject({movementMinor:600,expectedClosingMinor:2600,varianceMinor:0});
    await f.applied("after","EXPENSE_CREATE",{categoryId,amountMinor:10,method:"CASH",description:"After close"},"2026-10-06T19:00:00Z");
    const after=(await pool.query(`SELECT operating_day_id,staff_shift_id FROM cashbook_entries WHERE occurred_at='2026-10-06T19:00:00Z'`)).rows[0];expect(after).toEqual({operating_day_id:null,staff_shift_id:null});
    expect((await f.get("current")).json()).toMatchObject({operatingDay:null,shift:null,openShiftCount:0});
    expect((await pool.query(`SELECT COUNT(*) FROM audit_events WHERE event_type IN ('OPERATING_DAY_OPENED','OPERATING_DAY_CLOSED','SHIFT_OPENED','SHIFT_CLOSED')`)).rows[0].count).toBe("4");
    expect((await pool.query(`SELECT COUNT(*) FROM outbox_events WHERE event_type IN ('OPERATING_DAY_OPENED','OPERATING_DAY_CLOSED','SHIFT_OPENED','SHIFT_CLOSED')`)).rows[0].count).toBe("4");
  });
  it("recovers out-of-order offline movements that arrive before their day and shift open mutations",async()=>{
    const f=await fixture();
    const categoryId=(await pool.query(`SELECT id FROM expense_categories WHERE business_id=$1 LIMIT 1`,[f.businessId])).rows[0].id;
    await f.applied("early-arrival","EXPENSE_CREATE",{categoryId,amountMinor:100,method:"CASH",description:"Queued before opening"},"2026-10-06T10:00:00Z");
    expect((await pool.query(`SELECT operating_day_id,staff_shift_id FROM cashbook_entries WHERE business_id=$1`,[f.businessId])).rows[0]).toEqual({operating_day_id:null,staff_shift_id:null});
    await f.applied("future-arrival","EXPENSE_CREATE",{categoryId,amountMinor:50,method:"CASH",description:"Belongs after close"},"2026-10-06T19:00:00Z");
    const clientDayId=randomUUID();
    const day=await f.applied("late-day-open","OPERATING_DAY_OPEN_CREATE",{dayId:clientDayId,businessDate:"2026-10-06",openingBalances:[{method:"CASH",countedMinor:10000}]},"2026-10-06T09:00:00Z");
    expect(day.id).toBe(clientDayId);
    let entry=(await pool.query(`SELECT operating_day_id,staff_shift_id FROM cashbook_entries WHERE business_id=$1`,[f.businessId])).rows[0];
    expect(entry).toEqual({operating_day_id:day.id,staff_shift_id:null});
    const clientShiftId=randomUUID();
    const shift=await f.applied("late-shift-open","SHIFT_OPEN_CREATE",{dayId:day.id,shiftId:clientShiftId,openingBalances:[{method:"CASH",countedMinor:2000}]},"2026-10-06T09:30:00Z");
    expect(shift.id).toBe(clientShiftId);
    entry=(await pool.query(`SELECT operating_day_id,staff_shift_id FROM cashbook_entries WHERE business_id=$1`,[f.businessId])).rows[0];
    expect(entry).toEqual({operating_day_id:day.id,staff_shift_id:shift.id});
    const current=(await f.get("current")).json();
    expect(current.operatingDay.balances.find((b:any)=>b.method==="CASH")).toMatchObject({movementMinor:-150,expectedClosingMinor:9850});
    expect(current.shift.balances.find((b:any)=>b.method==="CASH")).toMatchObject({movementMinor:-150,expectedClosingMinor:1850});
    await f.applied("late-shift-close","SHIFT_CLOSE_CREATE",{shiftId:shift.id,closingBalances:counts(1900)},"2026-10-06T17:00:00Z");
    await f.applied("late-day-close","OPERATING_DAY_CLOSE_CREATE",{dayId:day.id,closingBalances:counts(9900)},"2026-10-06T18:00:00Z");
    const entries=(await pool.query(`SELECT occurred_at,operating_day_id,staff_shift_id FROM cashbook_entries WHERE business_id=$1 ORDER BY occurred_at`,[f.businessId])).rows;
    expect(entries[0]).toMatchObject({operating_day_id:day.id,staff_shift_id:shift.id});
    expect(entries[1]).toMatchObject({operating_day_id:null,staff_shift_id:null});
    const closed=(await f.get("days")).json().days[0];
    expect(closed.balances.find((b:any)=>b.method==="CASH")).toMatchObject({movementMinor:-100,expectedClosingMinor:9900,varianceMinor:0});
  });
  it("backfills a non-overlapping historical interval after a later interval is already closed",async()=>{
    const f=await fixture();
    const laterDay=await f.applied("later-day-open","OPERATING_DAY_OPEN_CREATE",{businessDate:"2026-10-07",openingBalances:counts(5000)},"2026-10-07T09:00:00Z");
    const laterShift=await f.applied("later-shift-open","SHIFT_OPEN_CREATE",{dayId:laterDay.id,openingBalances:counts(1000)},"2026-10-07T09:10:00Z");
    await f.applied("later-shift-close","SHIFT_CLOSE_CREATE",{shiftId:laterShift.id,closingBalances:counts(1000)},"2026-10-07T17:00:00Z");
    await f.applied("later-day-close","OPERATING_DAY_CLOSE_CREATE",{dayId:laterDay.id,closingBalances:counts(5000)},"2026-10-07T18:00:00Z");

    const historicalDay=await f.applied("historical-day-open","OPERATING_DAY_OPEN_CREATE",{businessDate:"2026-10-06",openingBalances:counts(4000)},"2026-10-06T09:00:00Z");
    const historicalShift=await f.applied("historical-shift-open","SHIFT_OPEN_CREATE",{dayId:historicalDay.id,openingBalances:counts(900)},"2026-10-06T09:10:00Z");
    await f.applied("historical-shift-close","SHIFT_CLOSE_CREATE",{shiftId:historicalShift.id,closingBalances:counts(900)},"2026-10-06T17:00:00Z");
    expect((await f.sync("historical-overlap-close","OPERATING_DAY_CLOSE_CREATE",{dayId:historicalDay.id,closingBalances:counts(4000)},"2026-10-07T10:00:00Z")).status).toBe("REJECTED");
    await f.applied("historical-day-close","OPERATING_DAY_CLOSE_CREATE",{dayId:historicalDay.id,closingBalances:counts(4000)},"2026-10-06T18:00:00Z");

    const days=(await f.get("days")).json().days;
    expect(days.map((day:any)=>day.businessDate)).toEqual(["2026-10-07","2026-10-06"]);
    expect(days.every((day:any)=>day.status==="CLOSED")).toBe(true);
  });
  it("serializes simultaneous opens, validates balances and rolls back unsafe movements",async()=>{
    const f=await fixture();
    const responses=await Promise.all([f.sync("day-a","OPERATING_DAY_OPEN_CREATE",{businessDate:"2026-10-06"}),f.sync("day-b","OPERATING_DAY_OPEN_CREATE",{businessDate:"2026-10-06"})]);
    expect(responses.map(r=>r.status).sort()).toEqual(["APPLIED","REJECTED"]);
    const shifts=await Promise.all([f.sync("shift-a","SHIFT_OPEN_CREATE",{}),f.sync("shift-b","SHIFT_OPEN_CREATE",{})]);
    expect(shifts.map(r=>r.status).sort()).toEqual(["APPLIED","REJECTED"]);
    const day=(await f.get("current")).json().operatingDay;
    const entry={businessId:f.businessId,branchId:f.branchId,amountDeltaMinor:Number.MAX_SAFE_INTEGER,currencyCode:"GHS",method:"CASH" as const,entryType:"ADJUSTMENT" as const,sourceType:"TEST",sourceId:randomUUID(),actorStaffId:f.actor,idempotencyKey:"safe",occurredAt:"2026-10-06T10:00:00Z"};
    await withTransaction(pool,c=>recordCashbookEntry(c,entry));
    await withTransaction(pool,c=>recordCashbookEntry(c,entry));
    await expect(withTransaction(pool,c=>recordCashbookEntry(c,{...entry,idempotencyKey:"overflow",amountDeltaMinor:1}))).rejects.toThrow();
    await expect(withTransaction(pool,c=>recordCashbookEntry(c,{...entry,amountDeltaMinor:1}))).rejects.toThrow("conflicts");
    expect((await pool.query(`SELECT COUNT(*) FROM cashbook_entries WHERE operating_day_id=$1`,[day.id])).rows[0].count).toBe("1");
    expect((await f.sync("bad-method","SHIFT_CLOSE_CREATE",{shiftId:shifts.find(r=>r.status==="APPLIED").result.id,closingBalances:[...counts(),{method:"CRYPTO",countedMinor:0}]})).status).toBe("REJECTED");
  });
  it("gates roles and own shifts, scopes reads and mutations to business/branch",async()=>{
    const f=await fixture();
    await pool.query(`UPDATE business_memberships SET role='CASHIER' WHERE business_id=$1`,[f.businessId]);
    expect((await f.request("cashier-day","OPERATING_DAY_OPEN_CREATE",{businessDate:"2026-10-06"})).statusCode).toBe(403);
    expect((await f.sync("no-day","SHIFT_OPEN_CREATE",{})).status).toBe("REJECTED");
    await pool.query(`UPDATE business_memberships SET role='OWNER' WHERE business_id=$1`,[f.businessId]);
    const day=await f.applied("day","OPERATING_DAY_OPEN_CREATE",{businessDate:"2026-10-06"});
    const otherStaff=(await pool.query(`INSERT INTO staff(business_id,display_name,role) VALUES ($1,'Other','CASHIER') RETURNING id`,[f.businessId])).rows[0].id;
    const other=await applyReconciliationMutation(pool,{businessId:f.businessId,branchId:f.branchId,clientMutationId:"other-shift",occurredAt:"2026-10-06T09:00:00Z"},{actorStaffId:otherStaff},"SHIFT_OPEN_CREATE");
    await pool.query(`UPDATE business_memberships SET role='CASHIER' WHERE business_id=$1`,[f.businessId]);
    const own=await f.applied("own-shift","SHIFT_OPEN_CREATE",{actorStaffId:otherStaff,staffId:otherStaff});
    expect((await f.get("shifts")).json().shifts.map((s:any)=>s.id)).toEqual([own.id]);
    expect((await f.sync("other-close","SHIFT_CLOSE_CREATE",{shiftId:other.id,closingBalances:counts(),actorStaffId:otherStaff})).status).toBe("REJECTED");
    await f.applied("own-close","SHIFT_CLOSE_CREATE",{shiftId:own.id,closingBalances:counts()},"2026-10-06T10:00:00Z");
    expect((await f.request("cashier-close-day","OPERATING_DAY_CLOSE_CREATE",{dayId:day.id,closingBalances:counts()})).statusCode).toBe(403);
    for(const role of ["OWNER","ADMIN","MANAGER","CASHIER","ACCOUNTANT","VIEWER"]){await pool.query(`UPDATE business_memberships SET role=$2 WHERE business_id=$1`,[f.businessId,role]);for(const resource of ["current","days","shifts"])expect((await f.get(resource)).statusCode).toBe(200);}
    for(const type of ["SHIFT_OPEN_CREATE","SHIFT_CLOSE_CREATE","OPERATING_DAY_OPEN_CREATE","OPERATING_DAY_CLOSE_CREATE"])expect((await f.request(`viewer-${type}`,type,{})).statusCode).toBe(403);
    for(const resource of ["current","days","shifts"]) expect((await app.inject({method:"GET",url:`/v1/operations/${resource}?businessId=${f.businessId}&branchId=${f.branchId}`})).statusCode).toBe(401);
    expect((await f.get("current","&limit=0")).statusCode).toBe(400);
    expect((await f.get("shifts","&dayId=invalid")).statusCode).toBe(400);
    expect((await f.get("days","&limit=1.5")).statusCode).toBe(400);
    const foreignBusiness=(await pool.query(`INSERT INTO businesses(name,business_type) VALUES ('Foreign','RETAIL_HARDWARE') RETURNING id`)).rows[0].id;
    const foreignBranch=(await pool.query(`INSERT INTO branches(business_id,name,code) VALUES ($1,'Foreign','FOREIGN') RETURNING id`,[foreignBusiness])).rows[0].id;
    for(const resource of ["current","days","shifts"]){expect((await app.inject({method:"GET",url:`/v1/operations/${resource}?businessId=${foreignBusiness}&branchId=${foreignBranch}`,headers:f.headers})).statusCode).toBe(403);expect((await app.inject({method:"GET",url:`/v1/operations/${resource}?businessId=${f.businessId}&branchId=${foreignBranch}`,headers:f.headers})).statusCode).toBe(404);}
    await pool.query(`UPDATE business_memberships SET role='OWNER' WHERE business_id=$1`,[f.businessId]);
    expect((await f.sync("foreign-branch","OPERATING_DAY_OPEN_CREATE",{businessDate:"2026-10-06"},undefined,foreignBranch)).status).toBe("REJECTED");
    expect((await f.get("shifts",`&dayId=${randomUUID()}`)).statusCode).toBe(404);
  });
});
