import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { buildApp } from "../src/app.js";
import { createPool } from "../src/db.js";
process.env.DATABASE_URL ??= "postgresql://tradeos:tradeos@127.0.0.1:5432/tradeos_ci";
const pool = createPool();
const app = buildApp(pool);
beforeAll(async () => { await app.ready(); });
beforeEach(async () => { await pool.query("TRUNCATE TABLE app_users,businesses CASCADE"); });
afterAll(async () => { await app.close(); await pool.end(); });

describe("purchase receiving and supplier payables", () => {
 it("converts bottles, snapshots glass COGS, restores return cost and pays credit once with authoritative actors", async () => {
  const registration = await app.inject({method:"POST",url:"/v1/auth/register",payload:{displayName:"Buyer",email:"buyer@tradeos.test",password:"TradeOS-Test-1234",platform:"WEB",deviceKey:"purchase-device",appVersion:"test"}});
  expect(registration.statusCode).toBe(201);
  const headers = {authorization:`Bearer ${registration.json().session.accessToken}`};
  const onboard = await app.inject({method:"POST",url:"/v1/onboarding/business",headers,payload:{name:"Bottle Shop",businessType:"DRINKING_SPOT",branchName:"Main"}});
  expect(onboard.statusCode).toBe(201);
  const businessId = onboard.json().business.id, branchId = onboard.json().branch.id;
  const supplierResponse = await app.inject({method:"POST",url:"/v1/suppliers",headers,payload:{businessId,name:"Whisky Supplier"}});
  expect(supplierResponse.statusCode).toBe(201);
  const supplierId = supplierResponse.json().supplier.id;
  const catalog = await app.inject({method:"POST",url:"/v1/catalog/items",headers,payload:{businessId,name:"Whisky",kind:"PRODUCT",trackStock:true,stockUnitCode:"ml",units:[{code:"ml",label:"ml",canStock:true},{code:"bottle",label:"Bottle",canPurchase:true},{code:"glass",label:"Glass",canSell:true,defaultSalePriceMinor:1800}],conversions:[{fromUnitCode:"bottle",toUnitCode:"ml",factor:750},{fromUnitCode:"glass",toUnitCode:"ml",factor:50}]}});
  expect(catalog.statusCode).toBe(201);
  const itemId = catalog.json().item.id;
  const sync = async (id:string,type:string,payload:unknown,branch=branchId) => {
   const response=await app.inject({method:"POST",url:"/v1/sync",headers,payload:{mutations:[{clientId:"purchase-device",clientMutationId:id,businessId,branchId:branch,mutationType:type,occurredAt:new Date().toISOString(),payload}]}});
   expect(response.statusCode).toBe(200);return response.json().mutationResults[0];
  };
  const receipt={supplierId,receivedByStaffId:"00000000-0000-4000-8000-000000000000",settlementMethod:"SUPPLIER_CREDIT",lines:[{itemId,purchaseUnitCode:"bottle",quantity:2,unitCostMinor:15000}]};
  const received=await sync("receipt-1","PURCHASE_RECEIVE_CREATE",receipt);
  expect(received.status).toBe("APPLIED");expect(received.result.totalMinor).toBe(30000);
  expect((await sync("receipt-1","PURCHASE_RECEIVE_CREATE",receipt)).status).toBe("APPLIED");
  const purchase=await pool.query(`SELECT received_by_staff_id FROM purchases`);
  const actor=await pool.query(`SELECT staff_id FROM business_memberships WHERE business_id=$1`,[businessId]);
  expect(purchase.rows[0].received_by_staff_id).toBe(actor.rows[0].staff_id);
  const inventory=await app.inject({method:"GET",url:`/v1/inventory?businessId=${businessId}&branchId=${branchId}`,headers});
  expect(inventory.json().items[0].available).toBe(1500);
  const sale=await sync("glass-sale","SALE_CREATE",{paymentMethod:"CASH",lines:[{itemId,saleUnitCode:"glass",quantity:2}]});
  expect(sale.status).toBe("APPLIED");
  const line=(await pool.query(`SELECT id,unit_cost_minor,line_cost_minor FROM sale_lines WHERE sale_id=$1`,[sale.result.saleId])).rows[0];
  expect(Number(line.unit_cost_minor)).toBe(1000);expect(Number(line.line_cost_minor)).toBe(2000);
  for(const disposition of ["RESTOCK","QUARANTINE"]) {
   expect((await sync(`return-${disposition}`,"RETURN_CREATE",{originalSaleId:sale.result.saleId,reason:"Wrong drink",refundMethod:"ORIGINAL_METHOD",lines:[{saleLineId:line.id,quantity:1,disposition}]})).status).toBe("APPLIED");
  }
  const valuations=(await pool.query(`SELECT location_type,quantity,value_minor FROM inventory_valuations ORDER BY location_type`)).rows;
  const availableValuation=valuations.find((row)=>row.location_type==="AVAILABLE");
  const quarantineValuation=valuations.find((row)=>row.location_type==="QUARANTINE");
  expect(Number(availableValuation.quantity)).toBe(1450);expect(Number(availableValuation.value_minor)).toBe(29000);
  expect(Number(quarantineValuation.quantity)).toBe(50);expect(Number(quarantineValuation.value_minor)).toBe(1000);
  const afterReturnInventory=await app.inject({method:"GET",url:`/v1/inventory?businessId=${businessId}&branchId=${branchId}`,headers});
  expect(afterReturnInventory.statusCode).toBe(200);
  expect(afterReturnInventory.json().items[0]).toMatchObject({available:1450,quarantine:50,inventoryValueMinor:30000});
  const balances=async()=> (await app.inject({method:"GET",url:`/v1/suppliers?businessId=${businessId}`,headers})).json().suppliers[0].balanceMinor;
  expect(await balances()).toBe(30000);
  const payment={supplierId,amountMinor:10000,method:"MOMO",paidByStaffId:receipt.receivedByStaffId};
  expect((await sync("payment-1","SUPPLIER_PAYMENT_CREATE",payment)).status).toBe("APPLIED");
  expect((await sync("payment-1","SUPPLIER_PAYMENT_CREATE",payment)).status).toBe("APPLIED");
  expect(await balances()).toBe(20000);
  const paymentActor = (await pool.query(`SELECT actor_staff_id FROM supplier_payable_ledger WHERE source_type='PAYMENT'`)).rows[0];
  expect(paymentActor.actor_staff_id).toBe(actor.rows[0].staff_id);
  expect((await sync("overpay","SUPPLIER_PAYMENT_CREATE",{...payment,amountMinor:20001})).errorCode).toBe("SUPPLIER_OVERPAYMENT");
  expect((await sync("bad-branch","PURCHASE_RECEIVE_CREATE",receipt,"00000000-0000-4000-8000-000000000000")).status).toBe("REJECTED");
  expect((await sync("bad-cost","PURCHASE_RECEIVE_CREATE",{...receipt,lines:[{...receipt.lines[0],unitCostMinor:Number.MAX_SAFE_INTEGER+1}]})).status).toBe("REJECTED");
  expect(await balances()).toBe(20000);
  expect(Number((await pool.query(`SELECT COUNT(*) FROM purchases`)).rows[0].count)).toBe(1);
  const paidReceipt={...receipt,settlementMethod:"BANK",lines:[{itemId,purchaseUnitCode:"bottle",quantity:2,unitCostMinor:30000}]};
  expect((await sync("paid-receipt","PURCHASE_RECEIVE_CREATE",paidReceipt)).status).toBe("APPLIED");
  expect(await balances()).toBe(20000);
  const averageSale=await sync("average-sale","SALE_CREATE",{paymentMethod:"CASH",lines:[{itemId,saleUnitCode:"glass",quantity:1}]});
  expect(averageSale.status).toBe("APPLIED");
  expect(Number((await pool.query(`SELECT line_cost_minor FROM sale_lines WHERE sale_id=$1`,[averageSale.result.saleId])).rows[0].line_cost_minor)).toBe(1508);
  const beforeFree=(await pool.query(`SELECT quantity,value_minor FROM inventory_valuations WHERE business_id=$1 AND branch_id=$2 AND item_id=$3 AND location_type='AVAILABLE'`,[businessId,branchId,itemId])).rows[0];
  const zeroCostCredit={...receipt,lines:[{itemId,purchaseUnitCode:"bottle",quantity:1,unitCostMinor:0}]};
  expect((await sync("zero-cost-credit","PURCHASE_RECEIVE_CREATE",zeroCostCredit)).status).toBe("APPLIED");
  expect(await balances()).toBe(20000);
  const afterFree=(await pool.query(`SELECT quantity,value_minor FROM inventory_valuations WHERE business_id=$1 AND branch_id=$2 AND item_id=$3 AND location_type='AVAILABLE'`,[businessId,branchId,itemId])).rows[0];
  expect(Number(afterFree.quantity)-Number(beforeFree.quantity)).toBe(750);
  expect(Number(afterFree.value_minor)).toBe(Number(beforeFree.value_minor));
  const concurrent=await Promise.all([sync("concurrent-pay-1","SUPPLIER_PAYMENT_CREATE",{...payment,amountMinor:15000}),sync("concurrent-pay-2","SUPPLIER_PAYMENT_CREATE",{...payment,amountMinor:15000})]);
  expect(concurrent.map(result=>result.status).sort()).toEqual(["APPLIED","REJECTED"]);
  expect(await balances()).toBe(5000);
 });

 it("carries purchased consumable cost into a service sale while reducing stock and valuation", async () => {
  const registration=await app.inject({method:"POST",url:"/v1/auth/register",payload:{displayName:"Salon Owner",email:"salon-procurement@tradeos.test",password:"TradeOS-Test-1234",platform:"WEB",deviceKey:"salon-procurement-device",appVersion:"test"}});
  expect(registration.statusCode).toBe(201);
  const headers={authorization:`Bearer ${registration.json().session.accessToken}`};
  const onboard=await app.inject({method:"POST",url:"/v1/onboarding/business",headers,payload:{name:"Costed Salon",businessType:"SALON_BARBER",branchName:"Main"}});
  expect(onboard.statusCode).toBe(201);
  const businessId=onboard.json().business.id, branchId=onboard.json().branch.id;
  const supplier=await app.inject({method:"POST",url:"/v1/suppliers",headers,payload:{businessId,name:"Salon Supplies"}});
  expect(supplier.statusCode).toBe(201);
  const supplierId=supplier.json().supplier.id;
  const shampoo=await app.inject({method:"POST",url:"/v1/catalog/items",headers,payload:{businessId,name:"Shampoo",kind:"PRODUCT",trackStock:true,stockUnitCode:"ml",units:[{code:"ml",label:"ml",canStock:true},{code:"bottle",label:"Bottle",canPurchase:true}],conversions:[{fromUnitCode:"bottle",toUnitCode:"ml",factor:1000}]}});
  expect(shampoo.statusCode).toBe(201);
  const shampooId=shampoo.json().item.id;
  const service=await app.inject({method:"POST",url:"/v1/catalog/items",headers,payload:{businessId,name:"Wash and set",kind:"SERVICE",units:[{code:"service",label:"Service",canSell:true,defaultSalePriceMinor:5000}]}});
  expect(service.statusCode).toBe(201);
  const serviceId=service.json().item.id;
  const definition=await pool.query<{id:string}>(`INSERT INTO consumption_definitions (business_id,output_item_id,output_quantity,output_unit_code) VALUES ($1,$2,1,'service') RETURNING id`,[businessId,serviceId]);
  await pool.query(`INSERT INTO consumption_components (definition_id,component_item_id,stock_unit_code,quantity_per_output,expected_waste_percent) VALUES ($1,$2,'ml',50,0)`,[definition.rows[0]!.id,shampooId]);
  const sync=async(id:string,type:string,payload:unknown)=>{
   const response=await app.inject({method:"POST",url:"/v1/sync",headers,payload:{mutations:[{clientId:"salon-procurement-device",clientMutationId:id,businessId,branchId,mutationType:type,occurredAt:new Date().toISOString(),payload}]}});
   expect(response.statusCode).toBe(200);return response.json().mutationResults[0];
  };
  const receipt=await sync("salon-shampoo-receipt","PURCHASE_RECEIVE_CREATE",{supplierId,settlementMethod:"CASH",receivedByStaffId:"00000000-0000-4000-8000-000000000000",lines:[{itemId:shampooId,purchaseUnitCode:"bottle",quantity:1,unitCostMinor:20000}]});
  expect(receipt.status).toBe("APPLIED");
  const sold=await sync("salon-service-sale","SALE_CREATE",{paymentMethod:"CASH",lines:[{itemId:serviceId,saleUnitCode:"service",quantity:1}]});
  expect(sold.status).toBe("APPLIED");
  const serviceLine=(await pool.query(`SELECT unit_cost_minor,line_cost_minor FROM sale_lines WHERE sale_id=$1`,[sold.result.saleId])).rows[0];
  expect(Number(serviceLine.unit_cost_minor)).toBe(1000);
  expect(Number(serviceLine.line_cost_minor)).toBe(1000);
  const stock=(await pool.query(`SELECT COALESCE(SUM(quantity_delta),0) AS quantity FROM inventory_movements WHERE business_id=$1 AND branch_id=$2 AND item_id=$3 AND location_type='AVAILABLE'`,[businessId,branchId,shampooId])).rows[0];
  expect(Number(stock.quantity)).toBe(950);
  const valuation=(await pool.query(`SELECT quantity,value_minor FROM inventory_valuations WHERE business_id=$1 AND branch_id=$2 AND item_id=$3 AND location_type='AVAILABLE'`,[businessId,branchId,shampooId])).rows[0];
  expect(Number(valuation.quantity)).toBe(950);
  expect(Number(valuation.value_minor)).toBe(19000);
  const movement=(await pool.query(`SELECT quantity_delta FROM inventory_movements WHERE item_id=$1 AND reason='SERVICE_CONSUMPTION'`,[shampooId])).rows[0];
  expect(Number(movement.quantity_delta)).toBe(-50);
 });
});
