import {describe,expect,it} from "vitest";import {buildDashboardModel,type DashboardEvidence} from "./dashboard-model";
const base=(overrides:Partial<DashboardEvidence>={}):DashboardEvidence=>({currencyCode:"GHS",source:"live",baselineLabel:"previous comparable period",report:{flow:{netRevenueMinor:125000,grossProfitMinor:45000,salesCount:12,cashInflowMinor:120000,cashOutflowMinor:20000,netCashMovementMinor:100000},comparison:{netRevenueChangePercent:12.5,grossProfitChangePercent:4.2},position:{cashBalanceMinor:800000,receivablesMinor:300000,payablesMinor:100000}},...overrides});
describe("dashboard deterministic evidence model",()=>{
 it("states a positive comparison baseline explicitly",()=>{const m=buildDashboardModel(base());expect(m.today.comparisonText).toContain("12.5% above previous comparable period");expect(m.momentum?.baselineLabel).toBe("previous comparable period");});
 it("states a negative comparison baseline explicitly",()=>{const e=base();e.report!.comparison!.netRevenueChangePercent=-8;expect(buildDashboardModel(e).today.comparisonText).toContain("8.0% below previous comparable period");});
 it("surfaces overdue receivables and cash shortfall as action items",()=>{const e=base({aging:{receivables:{overdue1To30DaysMinor:10000,overdue31To60DaysMinor:20000,overdue61To90DaysMinor:0,overdueOver90DaysMinor:5000}},forecast:{summary:{lowestProjectedCashMinor:-25000,firstNegativeCashDate:"2026-10-10"}}});const m=buildDashboardModel(e);expect(m.attention.some(a=>a.href==="/customers"&&a.amountMinor===35000)).toBe(true);expect(m.attention.some(a=>a.priority==="critical"&&a.href==="/cashbook")).toBe(true);});
 it("reports partial and unavailable coverage without inventing zeroes",()=>{const partial=buildDashboardModel(base({source:"partial",report:undefined}));expect(partial.today.netRevenueMinor).toBeNull();expect(partial.dataStatus.coverage).toContain("Partial");const none=buildDashboardModel({currencyCode:"USD",source:"unavailable",baselineLabel:"previous comparable period"});expect(none.today.netRevenueMinor).toBeNull();expect(none.pulse.summary).toContain("not enough saved business evidence");expect(none.currencyCode).toBe("USD");});
 it("produces deterministic pulse text without any AI field",()=>{const m=buildDashboardModel(base());expect(m.pulse.headline).toBeTruthy();expect(m.pulse.evidence.length).toBeGreaterThan(0);expect("aiText" in m.pulse).toBe(false);});
});
